arguments:
  parameters:
    - name: step-B-message
      value: hello
    - name: step-C-message
      value: world
    - name: step-D-message
      value: message
    - name: step-E-message
      value: some
    - name: step-F-message
      value: value
