arguments:
  parameters:
    - name: step-B-message
      value: hello
    - name: step-C-message
      value: message
    - name: step-E-message
      value: enter
    - name: step-E-name
      value: space
    - name: step-E-version
      value: 0.0.2
    - name: step-G-message
      value: world
    - name: step-G-name
      value: some
    - name: step-G-version
      value: 1.12
