arguments:
  parameters:
    - name: step-A-message
      value: hello
    - name: step-D-message
      value: world
    - name: step-D-name
      value: a
    - name: step-D-version
      value: b
    - name: step-E-message
      value: is
    - name: step-E-name
      value: c
    - name: step-E-version
      value: 1.12
    - name: step-G-message
      value: message
