arguments:
  parameters:
    - name: step-C-message
      value: hello
    - name: step-E-message
      value: some
    - name: step-E-name
      value: name
    - name: step-E-version
      value: 1.12
    - name: step-E-message
      value: world
    - name: step-E-name
      value: john
    - name: step-E-version
      value: 1.1.1
