apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: random-fail-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: A
        templateRef:
          name: random-fail
          template: random-fail
      - name: B
        templateRef:
          name: random-fail
          template: random-fail
        dependencies: [rand-fail-dag]
      - name: C
        templateRef:
          name: random-fail
          template: random-fail
        dependencies: [A, D]
      - name: D
        templateRef:
          name: random-fail
          template: random-fail
        dependencies: [A]
