apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: A
        templateRef:
          name: echo-timeout
          template: echo-timeout
        arguments:
          parameters:
          - name: timeout
            value: "{{workflow.parameters.A-timeout}}"
      - name: B
        templateRef:
          name: echo-timeout
          template: echo-timeout
        dependencies: [A]
        arguments:
          parameters:
          - name: timeout
            value: "{{workflow.parameters.B-timeout}}"
      - name: C
        templateRef:
          name: echo-timeout
          template: echo-timeout
        dependencies: [B]
        arguments:
          parameters:
          - name: timeout
            value: "{{workflow.parameters.C-timeout}}"
