apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: step-A
        templateRef:
          name: argocd-sync-output
          template: argocd-sync-and-wait
        arguments:
          parameters:
          - name: argocd-version
            value: "{{workflow.parameters.step-A-argocd-version}}"
          - name: application-name
            value: "{{workflow.parameters.step-A-application-name}}"
          - name: revision
            value: "{{workflow.parameters.step-A-revision}}"
          - name: flags
            value: "{{workflow.parameters.step-A-flags}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.step-A-argocd-server-address}}"
          - name: argocd-credentials-secret
            value: "{{workflow.parameters.step-A-argocd-credentials-secret}}"
      - name: step-B
        templateRef:
          name: whalesay-with-params1
          template: another-whalesay
        dependencies: [step-A]
        arguments:
          parameters:
          - name: test
            value: "{{workflow.parameters.step-B-test}}"
          - name: surname
            value: "{{tasks.step-B.outputs.parameters.surname}}"
      - name: step-C
        templateRef:
          name: whalesay-with-params1
          template: whalesay-template
        dependencies: [step-A]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-C-message}}"
          - name: name
            value: "{{workflow.parameters.step-C-name}}"
          - name: version
            value: "{{workflow.parameters.step-C-version}}"
      - name: step-D
        templateRef:
          name: root-step1
          template: suspend
        dependencies: [step-B]
        arguments:
