apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipe-name-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: step-A
        templateRef:
          name: root-step
          template: suspend
      - name: step-B
        templateRef:
          name: Select template
          template: Select subtemplate
        dependencies: [step-A]
      - name: step-C
        templateRef:
          name: whalesay
          template: whalesay-template
        dependencies: [step-A]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-C-message}}"
      - name: step-D
        templateRef:
          name: maintenance-step
          template: maintenance-mode
        dependencies: [step-C]
      - name: step-E
        templateRef:
          name: whalesay-with-params
          template: whalesay-template
        dependencies: [step-C]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-E-message}}"
          - name: name
            value: "{{workflow.parameters.step-E-name}}"
          - name: version
            value: "{{workflow.parameters.step-E-version}}"
      - name: step-E
        templateRef:
          name: whalesay-with-params
          template: whalesay-template
        dependencies: [step-B]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-E-message}}"
          - name: name
            value: "{{workflow.parameters.step-E-name}}"
          - name: version
            value: "{{workflow.parameters.step-E-version}}"
