apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: forever-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: step-A
        templateRef:
          name: forever
          template: forever
