apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coinflip-recursive-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: flip-coin
        templateRef:
          name: coinflip
          template: coinflip
      - name: heads
        templateRef:
          name: heads
          template: heads
        dependencies: [flip-coin]
      - name: tails
        templateRef:
          name: tails
          template: tails
        dependencies: [flip-coin]
