apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: log-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: A
        templateRef:
          name: gen-number-list
          template: gen-number-list
      - name: B
        templateRef:
          name: colored
          template: colored
        dependencies: [A]
      - name: C
        templateRef:
          name: echo
          template: print-message
        dependencies: [B]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.C-message}}"
