apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: step-A
        templateRef:
          name: gen-number-list
          template: gen-number-list
      - name: step-B
        templateRef:
          name: echo
          template: print-message
        dependencies: [step-A]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-B-message}}"
      - name: step-C
        templateRef:
          name: argosay
          template: argosay
        dependencies: [step-A]
      - name: step-D
        templateRef:
          name: maintenance-step
          template: maintenance-mode
        dependencies: [step-B, step-C]
