apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-pipe-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: step-A
        templateRef:
          name: root-step
          template: suspend
      - name: step-B
        templateRef:
          name: whalesay
          template: whalesay-template
        dependencies: [step-A]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-B-message}}"
