apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: colored-logs-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: colored-step
        templateRef:
          name: colored-logs
          template: colored
