apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coinflip-recursive-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: flip-coin
        templateRef:
          name: coinflip
          template: coinflip
      - name: heads
        templateRef:
          name: heads
          template: heads
        when: "{{steps.flip-coin.outputs.result}} == heads"
      - name: tails
        templateRef:
          name: tails
          template: tails
        when: "{{steps.flip-coin.outputs.result}} == tails"
