apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipe-name-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: step-A
        templateRef:
          name: maintenance-step
          template: maintenance-mode
      - name: step-B
        templateRef:
          name: root-step
          template: suspend
        dependencies: [step-A]
      - name: step-C
        templateRef:
          name: argocd-sync
          template: argocd-sync-and-wait
        dependencies: [step-A]
        arguments:
          parameters:
          - name: argocd-version
            value: "{{workflow.parameters.step-C-argocd-version}}"
          - name: application-name
            value: "{{workflow.parameters.step-C-application-name}}"
          - name: revision
            value: "{{workflow.parameters.step-C-revision}}"
          - name: flags
            value: "{{workflow.parameters.step-C-flags}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.step-C-argocd-server-address}}"
          - name: argocd-credentials-secret
            value: "{{workflow.parameters.step-C-argocd-credentials-secret}}"
      - name: step-D
        templateRef:
          name: whalesay
          template: whalesay-template
        dependencies: [step-A]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-D-message}}"
