apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: A
        templateRef:
          name: argocd-step
          template: argocd-sync-and-wait
        arguments:
          parameters:
          - name: argocd-version
            value: "{{workflow.parameters.A-argocd-version}}"
          - name: application-name
            value: "{{workflow.parameters.A-application-name}}"
          - name: revision
            value: "{{workflow.parameters.A-revision}}"
          - name: flags
            value: "{{workflow.parameters.A-flags}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.A-argocd-server-address}}"
          - name: argocd-credentials-secret
            value: "{{workflow.parameters.A-argocd-credentials-secret}}"
      - name: B
        templateRef:
          name: echo
          template: print-message
        dependencies: [A]
        arguments:
          parameters:
          - name: message
            value: "{{tasks.A.outputs.parameters.greenops-argocd-info}}"
