apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: coinflip-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: A
        templateRef:
          name: gen-number-list
          template: gen-number-list
      - name: B
        templateRef:
          name: maintenance-step
          template: maintenance-mode
        dependencies: [A]
      - name: C
        templateRef:
          name: coinflip
          template: coinflip
        dependencies: [A]
      - name: D
        templateRef:
          name: tails
          template: tails
        dependencies: [B, C]
