apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sidecar-step-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: sidecar-step
        templateRef:
          name: sidecar
          template: sidecar-example
