apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-pipe-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: step-A
        templateRef:
          name: test-template
          template: suspend-name
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-A-message}}"
      - name: step-B
        templateRef:
          name: whalesay-with-params
          template: whalesay-template
        dependencies: [step-A]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-B-message}}"
          - name: name
            value: "{{workflow.parameters.step-B-name}}"
          - name: version
            value: "{{workflow.parameters.step-B-version}}"
      - name: step-C
        templateRef:
          name: root-step
          template: suspend
        dependencies: [step-B]
      - name: step-D
        templateRef:
          name: whalesay
          template: whalesay-template
        dependencies: [step-C]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-D-message}}"
      - name: step-E
        templateRef:
          name: test-template
          template: suspend-name
        dependencies: [step-D]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-E-message}}"
      - name: step-G
        templateRef:
          name: whalesay-with-params
          template: whalesay-template
        dependencies: [step-D]
        arguments:
          parameters:
          - name: message
            value: "{{workflow.parameters.step-G-message}}"
          - name: name
            value: "{{workflow.parameters.step-G-name}}"
          - name: version
            value: "{{workflow.parameters.step-G-version}}"
