apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: 
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: A
        templateRef:
          name: coinflip
          template: coinflip
      - name: B
        templateRef:
          name: maintenance-step
          template: maintenance-mode
        dependencies: [A]
