apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipe-name-
spec:
  entrypoint: entry
  templates:
  - name: entry
    dag:
      tasks:
      - name: step-A
        templateRef:
          name: maintenance-step
          template: maintenance-mode
      - name: step-B
        templateRef:
          name: root-step
          template: suspend
        dependencies: [step-A]
